manifest:
  remotes:
    - name: zmk-firmware
      url-base: https://github.com/xqinx/zmk/tree
  projects:
    - name: thb
      remote: https://github.com/xqinx/zmk/tree
      revision: main
      import: app/west.yml
  self:
    path: config
