manifest:
  remotes:
    - name: codeandr3w
      url-base: https://github.com/codeandr3w/zmk-joystick
  projects:
    - name: codeandr3w
      remote: zmk-joystick
      revision: main
      import: app/west.yml
  self:
    path: config
