manifest:
  remotes:
    - name: zmk-joystick
      url-base: https://github.com/codeandr3w/zmk-joystick
  projects:
    - name: zmk
      remote: zmk-joystick
      revision: main
      import: app/west.yml
  self:
    path: config
