manifest:
  remotes:
    - name: xqinx
      url-base: https://github.com/xqinx
  projects:
    - name: zmk
      remote: https://github.com/xqinx
      revision: thb
      import: app/west.yml
  self:
    path: config
